"""
Argus — API & OpenAPI Route Discovery Engine

Automatically discovers endpoints by probing standard OpenAPI / Swagger spec locations
(e.g., /openapi.json, /swagger.json, /api-docs). Extracts all defined path routes
and generates a wordlist or returns candidate paths for scanning.
"""

import asyncio
import json
from pathlib import Path
from typing import List, Optional
import httpx

from core.auth_gate import ScanContext

OPENAPI_SPEC_PATHS = [
    "/openapi.json",
    "/swagger.json",
    "/api-docs",
    "/v2/api-docs",
    "/v3/api-docs",
    "/docs/openapi.json",
    "/docs.json"
]


async def discover_api_routes(
    base_url: str,
    ctx: ScanContext,
    output_wordlist: Optional[str] = None,
) -> List[str]:
    """
    Probes base_url for OpenAPI / Swagger specs and extracts all path routes.
    If output_wordlist is specified, writes the routes to the wordlist file.
    """
    ctx.assert_in_scope(base_url)
    discovered_paths = set()

    async with httpx.AsyncClient() as client:
        for spec_path in OPENAPI_SPEC_PATHS:
            await ctx.throttle()
            url = f"{base_url.rstrip('/')}{spec_path}"
            try:
                resp = await client.get(url, timeout=5.0, follow_redirects=True)
                if resp.status_code == 200:
                    try:
                        data = resp.json()
                        if isinstance(data, dict) and "paths" in data:
                            paths = data.get("paths", {})
                            for route in paths.keys():
                                # Normalize route (strip leading slash)
                                clean_route = route.lstrip("/")
                                if clean_route:
                                    discovered_paths.add(clean_route)
                    except json.JSONDecodeError:
                        pass
            except httpx.RequestError:
                continue

    routes_list = sorted(list(discovered_paths))

    if output_wordlist and routes_list:
        out_path = Path(output_wordlist)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write("# Automatically generated by Argus API Discovery\n")
            for route in routes_list:
                f.write(f"{route}\n")

    return routes_list
